#:schema node_modules/wrangler/config-schema.json
name = "bgp-inspector"
compatibility_date = "2026-03-21"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
# RADAR_API_TOKEN = ""

[[routes]]
pattern = "rov.bgpkit.com"
custom_domain = true
